(function(){
  const frame=document.getElementById('app');
  const statusMap={new:'جديد',contacted:'تم التواصل',agreed:'وافق',ready:'جاهز',no:'لا يريد',no_reply:'لا يوجد رد'};
  const marketMap={ready:'جاهز للتسويق',not_ready:'غير جاهز للتسويق'};
  function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
  function fmt(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?esc(v):d.toLocaleString('ar-OM',{dateStyle:'medium',timeStyle:'short'})}
  function boot(){
    try{
      const w=frame.contentWindow,d=frame.contentDocument;if(!w||!d?.body)return;
      if(!d.getElementById('crmEnhStyle')){const s=d.createElement('style');s.id='crmEnhStyle';s.textContent=`
        .crm-file-btn{margin-inline-start:6px;border:1px solid #42658c;background:linear-gradient(135deg,#163a5f,#1b2750);color:#fff;padding:8px 10px;border-radius:10px;font-size:10px}
        .crm-file{display:grid;gap:12px}.crm-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.crm-stat{padding:10px;border:1px solid #244868;border-radius:12px;background:linear-gradient(135deg,#10263f,#0a1728)}.crm-stat b{display:block;font-size:16px}.crm-stat small{color:#90a7c1;font-size:9px}.crm-next{padding:11px;border-radius:13px;border:1px solid #315a7e;background:linear-gradient(135deg,rgba(66,221,255,.10),rgba(107,120,255,.12))}.crm-next b{color:#42ddff}.crm-timeline{display:grid;gap:8px;max-height:300px;overflow:auto}.crm-event{padding:10px;border:1px solid #203e5b;border-radius:12px;background:#0b1a2c}.crm-event-top{display:flex;justify-content:space-between;gap:8px}.crm-event-top b{font-size:11px}.crm-event-top span{font-size:9px;color:#90a7c1}.crm-event p{margin:6px 0 0;color:#c7d6e8;font-size:10px;line-height:1.6}.crm-props{display:grid;gap:7px}.crm-prop{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:9px;border:1px solid #203e5b;border-radius:11px}.crm-prop small{display:block;color:#90a7c1;margin-top:3px;font-size:9px}.crm-edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.crm-wide{grid-column:1/-1}@media(max-width:650px){.crm-summary{grid-template-columns:1fr 1fr}.crm-edit-grid{grid-template-columns:1fr}.crm-wide{grid-column:auto}}
      `;d.head.appendChild(s)}
      const rows=[...d.querySelectorAll('#orows tr')];
      rows.forEach(tr=>{if(tr.dataset.enhanced==='1')return;const btn=tr.querySelector('button[onclick^="editOwner("]');if(!btn)return;const m=String(btn.getAttribute('onclick')).match(/editOwner\('([^']+)'\)/);if(!m)return;const id=m[1];tr.dataset.enhanced='1';const b=d.createElement('button');b.className='crm-file-btn';b.textContent='ملف العمل';b.onclick=()=>showOwner(id);const cell=tr.lastElementChild;if(cell)cell.appendChild(b)})
      const oldOpen=w.openModal;
      w.showOwner=showOwner;
      function showOwner(id){
        const o=(w.D?.owners||[]).find(x=>String(x.id)===String(id));if(!o)return;
        const props=(w.D?.ownerProperties||[]).filter(x=>String(x.owner_id)===String(id)).map(x=>w.D.ads.find(a=>String(a.id)===String(x.ad_id))).filter(Boolean);
        const contacts=(w.D?.ownerContacts||[]).filter(x=>String(x.owner_id)===String(id)).sort((a,b)=>Date.parse(b.contacted_at||0)-Date.parse(a.contacted_at||0));
        const next= o.status==='new' ? 'إجراء الآن: التواصل الأول مع المالك.' : o.status==='contacted' ? 'الإجراء التالي: توثيق نتيجة الاتصال وتحديد موعد متابعة.' : o.status==='agreed' && o.marketing_status!=='ready' ? 'الإجراء التالي: استكمال بيانات العقار والحصول على موافقة التسويق.' : o.status==='ready' ? 'الإجراء التالي: تسويق العقار ومطابقته مع الطلبات النشطة.' : o.status==='no_reply' ? 'الإجراء التالي: إعادة المحاولة في موعد مناسب.' : o.status==='no' ? 'لا توجد متابعة تسويقية حتى يغيّر المالك موقفه.' : 'راجع حالة المالك وحدد الخطوة التالية.';
        const timeline=contacts.length?contacts.map(c=>`<div class="crm-event"><div class="crm-event-top"><b>${esc(statusMap[c.outcome]||c.outcome||'تواصل')}</b><span>${fmt(c.contacted_at)}</span></div>${c.notes?`<p>${esc(c.notes)}</p>`:''}${c.next_followup_at?`<p>المتابعة القادمة: ${fmt(c.next_followup_at)}</p>`:''}</div>`).join(''):'<div class="empty">لا يوجد سجل تواصل بعد.</div>';
        const plist=props.length?props.map(a=>`<div class="crm-prop"><div><b>${esc(a.name||'عقار')}</b><small>${esc(a.area||'—')} • ${esc(a.type||'—')} • ${w.mon(a)?Math.round(w.mon(a))+' ر.ع/شهر':'سعر غير محدد'}</small></div><span class="pill ${w.score(a)>=75?'good':w.score(a)>=55?'yellow':'red'}">${w.score(a)}</span></div>`).join(''):'<div class="empty">لا توجد عقارات مربوطة.</div>';
        oldOpen('ملف المالك — '+(o.owner_name||'بدون اسم'),`<div class="crm-file"><div class="crm-summary"><div class="crm-stat"><b>${esc(statusMap[o.status]||o.status||'جديد')}</b><small>الحالة</small></div><div class="crm-stat"><b>${esc(marketMap[o.marketing_status]||'غير جاهز')}</b><small>التسويق</small></div><div class="crm-stat"><b>${props.length}</b><small>العقارات</small></div><div class="crm-stat"><b>${o.next_followup_at?fmt(o.next_followup_at):'غير محدد'}</b><small>المتابعة القادمة</small></div></div><div class="crm-next"><b>الخطوة التالية</b><div class="muted" style="margin-top:5px">${esc(next)}</div></div><div class="panel" style="margin:0"><div class="head"><h2>عقارات المالك</h2></div><div class="crm-props">${plist}</div></div><div class="panel" style="margin:0"><div class="head"><h2>سجل التواصل</h2><span class="muted">${contacts.length} تواصل</span></div><div class="crm-timeline">${timeline}</div></div><div class="actions-row"><button class="btn primary" onclick="crmEditOwner('${id}')">تعديل بيانات العمل</button><button class="btn good" onclick="contact('${id}')">تسجيل تواصل جديد</button><button class="btn" onclick="closeModal()">إغلاق</button></div></div>`)
      }
      w.crmEditOwner=function(id){const o=(w.D?.owners||[]).find(x=>String(x.id)===String(id));if(!o)return;oldOpen('بيانات العمل — '+(o.owner_name||'مالك'),`<div class="crm-edit-grid"><input id="crm_fn" class="field" placeholder="اسم المالك" value="${esc(o.owner_name)}"><input id="crm_fp" class="field" placeholder="الهاتف" value="${esc(o.phone)}"><select id="crm_fs" class="field"><option value="new">جديد</option><option value="contacted">تم التواصل</option><option value="agreed">وافق</option><option value="ready">جاهز</option><option value="no">لا يريد</option><option value="no_reply">لا يوجد رد</option></select><select id="crm_fm" class="field"><option value="not_ready">غير جاهز</option><option value="ready">جاهز للتسويق</option></select><input id="crm_nf" class="field" type="datetime-local" value="${o.next_followup_at?new Date(o.next_followup_at).toISOString().slice(0,16):''}"><input id="crm_comm" class="field" placeholder="ملاحظات العمولة" value="${esc(o.commission_notes)}"><textarea id="crm_notes" class="field crm-wide" rows="4" placeholder="ملاحظات العمل">${esc(o.notes)}</textarea></div><div class="actions-row"><button class="btn primary" onclick="crmSaveOwner('${id}')">حفظ</button><button class="btn" onclick="showOwner('${id}')">سجل المالك</button><button class="btn" onclick="closeModal()">إلغاء</button></div>`);d.getElementById('crm_fs').value=o.status||'new';d.getElementById('crm_fm').value=o.marketing_status||'not_ready'};
      w.crmSaveOwner=async function(id){try{await w.api('owner_upsert',{owner:{id,owner_name:d.getElementById('crm_fn').value,phone:d.getElementById('crm_fp').value,status:d.getElementById('crm_fs').value,marketing_status:d.getElementById('crm_fm').value,next_followup_at:d.getElementById('crm_nf').value?new Date(d.getElementById('crm_nf').value).toISOString():null,commission_notes:d.getElementById('crm_comm').value,notes:d.getElementById('crm_notes').value}});w.closeModal();await w.load();setTimeout(()=>showOwner(id),300)}catch(e){w.toast(e.message)}};
    }catch(e){console.error('crm enhancement',e)}
  }
  frame.addEventListener('load',()=>{boot();setInterval(boot,900)});
})();
