(function(){
  const frame=document.getElementById('app');
  function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
  function digits(v){return String(v||'').replace(/[^0-9]/g,'')}
  function phoneFor(v){let p=digits(v);if(!p)return '';if(p.startsWith('00'))p=p.slice(2);if(p.length===8&&/^[79]/.test(p))p='968'+p;if(p.startsWith('968968'))p=p.slice(3);return p}
  function propertyUrl(id){return window.location.origin+window.location.pathname+'#property='+encodeURIComponent(String(id))}
  function syncDeepLink(w){try{const m=(window.location.hash||'').match(/^#property=(.+)$/);if(m&&w?.location){const id=decodeURIComponent(m[1]);const h='#property='+encodeURIComponent(id);if(w.location.hash!==h)w.location.hash=h}}catch(e){}}
  function boot(){try{
    const w=frame.contentWindow,d=frame.contentDocument;if(!w||!d?.body||!w.D)return;
    syncDeepLink(w);
    if(!d.getElementById('propActionsStyle')){const s=d.createElement('style');s.id='propActionsStyle';s.textContent='.prop-actions{display:flex;gap:5px;flex-wrap:wrap;align-items:center}.prop-actions .btn{padding:7px 9px;font-size:9px}.prop-details{display:grid;gap:10px}.prop-details-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.prop-detail{padding:9px;border:1px solid #244868;border-radius:11px;background:#0b1a2c}.prop-detail b{display:block;color:#42ddff;font-size:9px;margin-bottom:4px}.prop-detail span{font-size:11px;white-space:pre-wrap;line-height:1.7}.prop-actions .whatsapp{color:#75e39b;border-color:#2e704d}.prop-actions .call{color:#b7f4ff;border-color:#315a7e}@media(max-width:650px){.prop-details-grid{grid-template-columns:1fr}.prop-actions .btn{flex:1;min-width:78px}}';d.head.appendChild(s)}
    [...d.querySelectorAll('#prows tr')].forEach(tr=>{if(tr.dataset.propActions==='1')return;const idText=tr.querySelector('td .muted')?.textContent||'';const m=idText.match(/#(.+)$/);if(!m)return;const id=m[1].trim(),a=(w.D.ads||[]).find(x=>String(x.id)===id);if(!a)return;const cell=tr.lastElementChild;if(!cell)return;const old=[...cell.querySelectorAll('button')];const wrap=d.createElement('div');wrap.className='prop-actions';const add=(label,cls,fn)=>{const b=d.createElement('button');b.type='button';b.className='btn '+(cls||'');b.textContent=label;b.onclick=fn;wrap.appendChild(b)};if(a.phone){add('واتساب','good whatsapp',()=>{const p=phoneFor(a.phone);if(p)w.open('https://wa.me/'+p,'_blank');else w.toast?.('رقم الهاتف غير صالح')});add('اتصال','call',()=>{const p=phoneFor(a.phone);if(p)w.location.href='tel:+'+p;else w.toast?.('رقم الهاتف غير صالح')})}add('تفاصيل','',()=>showDetails(a));add('مشاركة','cyan',()=>shareProperty(a));old.forEach(b=>wrap.appendChild(b));cell.innerHTML='';cell.appendChild(wrap);tr.dataset.propActions='1'});
    w.propShare=shareProperty;
    async function shareProperty(a){const url=propertyUrl(a.id),text=[a.name||'عقار',a.area||'',a.type||'',a.price?String(a.price)+' '+(a.period||''):''].filter(Boolean).join(' • ');try{if(navigator.share){await navigator.share({title:a.name||'عقار في صحار',text,url});w.toast?.('تمت مشاركة رابط العقار');return}}catch(e){if(e?.name==='AbortError')return}try{await navigator.clipboard.writeText(url);w.toast?.('تم نسخ رابط العقار')}catch(_){try{w.prompt('رابط مشاركة العقار',url)}catch(e){}}}
    function showDetails(a){const p=phoneFor(a.phone),o=typeof w.owner==='function'?w.owner(a):null,m=typeof w.mon==='function'?w.mon(a):null,b=typeof w.bench==='function'?w.bench(a):null,s=typeof w.score==='function'?w.score(a):null;const src=a.url?`<a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer" class="btn cyan">فتح الإعلان الأصلي</a>`:'';const contact=p?`<button class="btn good" onclick="window.open('https://wa.me/${p}','_blank')">واتساب</button><a class="btn call" href="tel:+${p}">اتصال</a>`:'';const shareBtn=`<button class="btn cyan" onclick="propShare(${JSON.stringify(a.id)})">مشاركة العقار</button>`;const locationBlock=a.lat&&a.lng?`<div class="prop-detail"><b>الموقع</b><span>${esc(a.lat)}, ${esc(a.lng)}</span></div>`:'';w.openModal('تفاصيل العقار — '+(a.name||'عقار'),`<div class="prop-details"><div class="prop-details-grid"><div class="prop-detail"><b>النوع</b><span>${esc(a.type||'—')}</span></div><div class="prop-detail"><b>المنطقة</b><span>${esc(a.area||'—')}</span></div><div class="prop-detail"><b>السعر</b><span>${esc(a.price||'—')} ${esc(a.period||'')}</span></div><div class="prop-detail"><b>شهري تقريبي</b><span>${m?Math.round(m)+' ر.ع':'—'}</span></div><div class="prop-detail"><b>مرجع السوق</b><span>${b?Math.round(b)+' ر.ع':'—'}</span></div><div class="prop-detail"><b>درجة الفرصة</b><span>${s!=null?s:'—'}</span></div><div class="prop-detail"><b>المالك</b><span>${esc(o?.owner_name||'غير مربوط')}</span></div><div class="prop-detail"><b>الهاتف</b><span>${esc(a.phone||'—')}</span></div>${locationBlock}</div><div class="prop-detail"><b>التفاصيل</b><span>${esc(a.details||'لا توجد تفاصيل')}</span></div>${a.photo?`<img src="${esc(a.photo)}" alt="صورة العقار" style="max-width:100%;max-height:280px;border-radius:12px;object-fit:contain">`:''}<div class="actions-row">${src}${contact}${shareBtn}<button class="btn" onclick="closeModal()">إغلاق</button></div></div>`)}
    const hm=(w.location.hash||'').match(/^#property=(.+)$/);if(hm){const a=(w.D.ads||[]).find(x=>String(x.id)===decodeURIComponent(hm[1]));if(a)setTimeout(()=>showDetails(a),250)}
  }catch(e){console.error('property actions',e)}}
  frame.addEventListener('load',()=>{boot();setInterval(boot,800)});
  window.addEventListener('hashchange',()=>{try{syncDeepLink(frame.contentWindow);setTimeout(boot,250)}catch(e){}});
  window.addEventListener('message',e=>{if(e.data?.type==='sohar-property-share'&&e.data.id){window.location.hash='property='+encodeURIComponent(String(e.data.id))}});
})();
