(function(){
  const frame=document.getElementById('app');
  function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
  function digits(v){return String(v||'').replace(/[^0-9]/g,'')}
  function phoneFor(v){let p=digits(v);if(!p)return '';if(p.startsWith('00'))p=p.slice(2);if(p.length===8&&/^[79]/.test(p))p='968'+p;if(p.startsWith('968968'))p=p.slice(3);return p}
  function propertyUrl(id){return window.location.origin+window.location.pathname+'?property='+encodeURIComponent(String(id))}
  function shareProperty(a){const url=propertyUrl(a.id),text=[a.name||'عقار',a.area||'',a.type||'',a.price?String(a.price)+' '+(a.period||''):''].filter(Boolean).join(' • ');return (async()=>{try{if(navigator.share){await navigator.share({title:a.name||'عقار في صحار',text,url});return}}catch(e){if(e?.name==='AbortError')return}try{await navigator.clipboard.writeText(url);alert('تم نسخ رابط العقار')}catch(e){try{const ta=document.createElement('textarea');ta.value=url;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.focus();ta.select();document.execCommand('copy');ta.remove();alert('تم نسخ رابط العقار')}catch(_){prompt('رابط مشاركة العقار',url)}}})()}
  function showDetails(w,a){const d=frame.contentDocument,p=phoneFor(a.phone),o=typeof w.owner==='function'?w.owner(a):null,m=typeof w.mon==='function'?w.mon(a):null,b=typeof w.bench==='function'?w.bench(a):null,s=typeof w.score==='function'?w.score(a):null;const src=a.url?`<a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer" class="btn cyan">فتح الإعلان الأصلي</a>`:'';const contact=p?`<button class="btn good" data-detail-wa="1">واتساب</button><a class="btn call" href="tel:+${p}">اتصال</a>`:'';w.openModal('تفاصيل العقار — '+(a.name||'عقار'),`<div class="prop-details"><div class="prop-details-grid"><div class="prop-detail"><b>النوع</b><span>${esc(a.type||'—')}</span></div><div class="prop-detail"><b>المنطقة</b><span>${esc(a.area||'—')}</span></div><div class="prop-detail"><b>السعر</b><span>${esc(a.price||'—')} ${esc(a.period||'')}</span></div><div class="prop-detail"><b>شهري تقريبي</b><span>${m?Math.round(m)+' ر.ع':'—'}</span></div><div class="prop-detail"><b>مرجع السوق</b><span>${b?Math.round(b)+' ر.ع':'—'}</span></div><div class="prop-detail"><b>درجة الفرصة</b><span>${s!=null?s:'—'}</span></div><div class="prop-detail"><b>المالك</b><span>${esc(o?.owner_name||'غير مربوط')}</span></div><div class="prop-detail"><b>الهاتف</b><span>${esc(a.phone||'—')}</span></div>${a.lat&&a.lng?`<div class="prop-detail"><b>الموقع</b><span>${esc(a.lat)}, ${esc(a.lng)}</span></div>`:''}</div><div class="prop-detail"><b>التفاصيل</b><span>${esc(a.details||'لا توجد تفاصيل')}</span></div>${a.photo?`<img src="${esc(a.photo)}" alt="صورة العقار" style="max-width:100%;max-height:280px;border-radius:12px;object-fit:contain">`:''}<div class="actions-row">${src}${contact}<button class="btn cyan" data-detail-share="1">مشاركة العقار</button><button class="btn" data-detail-close="1">إغلاق</button></div></div>`);const modal=d.querySelector('[data-detail-wa]');if(modal)modal.onclick=()=>window.open('https://wa.me/'+p,'_blank');const sh=d.querySelector('[data-detail-share]');if(sh)sh.onclick=()=>shareProperty(a);const cl=d.querySelector('[data-detail-close]');if(cl)cl.onclick=()=>w.closeModal?.()}
  function addPropertyActions(w,d){const body=d.getElementById('prows');if(!body)return;[...body.querySelectorAll('tr')].forEach(tr=>{if(tr.dataset.propActions==='1')return;const idText=tr.textContent||'';const m=idText.match(/#(\d+)\b/);const id=m?m[1]:null;if(!id)return;const a=(w.D.ads||[]).find(x=>String(x.id)===id);if(!a)return;let cell=tr.lastElementChild;if(!cell)return;const wrap=d.createElement('div');wrap.className='prop-actions';const add=(label,cls,fn)=>{const b=d.createElement('button');b.type='button';b.className='btn '+(cls||'');b.textContent=label;b.onclick=fn;wrap.appendChild(b)};if(a.phone){add('واتساب','good whatsapp',()=>{const p=phoneFor(a.phone);if(p)w.open('https://wa.me/'+p,'_blank')});add('اتصال','call',()=>{const p=phoneFor(a.phone);if(p)w.location.href='tel:+'+p})}add('تفاصيل','',()=>showDetails(w,a));add('مشاركة','cyan',()=>shareProperty(a));const old=[...cell.querySelectorAll('button,a')];old.forEach(x=>{if(!/^(واتساب|اتصال|تفاصيل|مشاركة)$/.test(x.textContent?.trim()||''))wrap.appendChild(x)});cell.innerHTML='';cell.appendChild(wrap);tr.dataset.propActions='1'})}
  function boot(){try{const w=frame.contentWindow,d=frame.contentDocument;if(!w||!d?.body||!w.D)return;if(!d.getElementById('propActionsStyle')){const s=d.createElement('style');s.id='propActionsStyle';s.textContent='.prop-actions{display:flex;gap:6px;flex-wrap:wrap;align-items:center;justify-content:flex-start}.prop-actions .btn{padding:7px 10px;font-size:10px;min-height:32px}.prop-actions .whatsapp{color:#75e39b;border-color:#2e704d}.prop-actions .call{color:#b7f4ff;border-color:#315a7e}.prop-details{display:grid;gap:10px}.prop-details-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.prop-detail{padding:9px;border:1px solid #244868;border-radius:11px;background:#0b1a2c}.prop-detail b{display:block;color:#42ddff;font-size:9px;margin-bottom:4px}.prop-detail span{font-size:11px;white-space:pre-wrap;line-height:1.7}@media(max-width:700px){.prop-actions .btn{flex:1;min-width:78px}.prop-details-grid{grid-template-columns:1fr}}';d.head.appendChild(s)}
    if(!w.__soharPropRenderWrapped&&typeof w.renderProps==='function'){const orig=w.renderProps;w.renderProps=function(){const r=orig.apply(this,arguments);setTimeout(()=>addPropertyActions(w,d),0);return r};w.__soharPropRenderWrapped=true}
    addPropertyActions(w,d);if(!bodyObserver(d)){bodyObserver(d)}
    w.__soharShareProperty=id=>{const a=(w.D.ads||[]).find(x=>String(x.id)===String(id));if(a)shareProperty(a)};
  }catch(e){console.error('property actions',e)}}
  function bodyObserver(d){const body=d.getElementById('prows');if(!body||body.__soharObs)return true;const o=new MutationObserver(()=>setTimeout(()=>{try{const w=frame.contentWindow;if(w?.D)addPropertyActions(w,d)}catch(e){}},0));o.observe(body,{childList:true,subtree:true});body.__soharObs=true;return true}
  frame.addEventListener('load',()=>{boot();setTimeout(boot,300);setTimeout(boot,1000);setInterval(boot,2500)});
})();